language: r
sudo: required
cache: packages
apt_packages:
- libudunits2-dev
- libgdal-dev
- libspatialite-dev
r_packages:
- remotes
- covr
matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
